name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "major, minor or patch"
        required: true

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Generate Deploy tag for prod
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./scripts/deploy.sh -v ${{ github.event.inputs.version }}
